logging:
  level:
    com.guanke.vinda: DEBUG

server:
  port: 8103

spring:
  application:
    name: sa-wx
  profiles:
    active: dev

tencent:
  mapKey: 6NJBZ-DFDAG-6QWQC-I55XF-IR4Z5-3GBLY
  secretKey: L7eAGBrwPbFjSbKbsiLiK6KjdVzd454a