spring:
  profiles:
    active: dev
  application:
    name: sa-core

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetchRegistry: false