spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: vddb
    url: jdbc:mysql://${MYSQL_HOST:10.10.109.251}:${MYSQL_PORT:3306}/vddb?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    username: guanke
    password: Guanke12#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,log4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: druidAdmin
        login-password: druidAdmin1234!
      filter:
        commons-log:
          statement-executable-sql-log-enable: true
        log4j:
          enabled: true
          connection-log-enabled: true
          connection-log-error-enabled: true
          statement-log-error-enabled: true
          result-set-log-enabled: true
  redis:
    host: ${REDIS_HOST:10.100.240.124}
    port: ${REDIS_PORT:16379}
    jedis:
      pool:
        max-wait: 10000
        max-active: 50
        max-idle: 30
        min-idle: 0
    timeout: 5000
    password: salesaux


#    rabbitmq:
#      host: ${RABBIT_MQ_HOST:yytest.vinda.com}
#      port:  ${RABBIT_MQ_PORT:18058}
#      username: ${RABBIT_MQ_USERNAME:guest}
#      password: ${RABBIT_MQ_PASSWORD:guest}

# 配置数据库
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  config-location: classpath:mapper/config/mybatis-configuration.xml
eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
    prefer-ip-address: true
    ip-address: ${EUREKA_HOST:localhost}
    leaseRenewalIntervalInSeconds: 5
    hostname: sa-func
  client:
    serviceUrl:
      # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

#ribbon:
#  eureka:
#    enabled: true
#  ReadTimeout: 120000
#  ConnectTimeout: 120000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 0
#  OkToRetryOnAllOperations: false
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 1000
#      maxQueueSize: 1000
#      queueSizeRejectionThreshold: 500
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 50000

# 配置用户认证和服务认证信息
#auth:
#  serviceId: ace-auth
#  user:
#    token-header: Authorization
#    limit-expire: 1440 # 一天过去,单位分钟
#  client:
#    id: sa-func
#    secret: 123456
#    token-header: client-token

# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop: # 启动注解的方式,自动聚合
    enabled: true

wx:
  corpId: ww41012b98245950a2
  agentId: 1000002
  secret: HxrpE6vXOYsVjkkkuCwSxUlERmsKWr20iCBnn14iI4c

